version: "3"
services:
  front:
    image: node:14.15.4-buster-slim
    volumes:
      - ./:/usr/src
      - front_modules:/usr/src/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
volumes:
  front_modules:
